export { getStateName } from 'entities/Name/models/selectors/getStateName/getStateName'
export { getName } from 'entities/Name/models/selectors/getName/getName'
export { setName } from './models/slice/nameSlice'
export { nameReducer } from './models/slice/nameSlice'
export type { NameSchema } from './models/types/NameType'
